In [5]:
import tensorflow as tf

## 문자열 출력

In [6]:
hello=tf.constant("Hello,Tensorflow!")
tf.print(hello)

Hello,Tensorflow!


## 덧셈

In [11]:
tf.add(2,3)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

## 뺄셈

In [12]:
tf.subtract(2,3)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

## 곱셈

In [13]:
tf.multiply(2,3)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

## 나눗셈

In [14]:
tf.divide(2,3)

<tf.Tensor: shape=(), dtype=float64, numpy=0.6666666666666666>

## n-제곱

In [15]:
tf.pow(2,3)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

## 음수부호

In [16]:
tf.negative(2)

<tf.Tensor: shape=(), dtype=int32, numpy=-2>

## 절대값

In [17]:
tf.abs(-2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## 부호

In [18]:
tf.sign(-2)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

## 반올림

In [19]:
tf.round(1.2)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

## 올림

In [21]:
tf.math.ceil(1.2)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

## 내림

In [22]:
tf.floor(1.2)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

## 제곱

In [23]:
tf.math.square(-2)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

## 제곱근

In [27]:
A=tf.constant(4,tf.float32)
tf.math.sqrt(A)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

## 누적합

In [30]:
B=tf.constant([2,4,6,8])
tf.cumsum(B)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2,  6, 12, 20])>

## 누적곱

In [31]:
C=tf.constant([2,4,6,8])
tf.math.cumprod(C)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([  2,   8,  48, 384])>

## 최댓값

In [32]:
tf.maximum(2,3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

## 최솟값

In [33]:
tf.minimum(2,3)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Tensor = data array
## Tensor Ranks = 몇차원데이터
## Tensor Shapes = 차원데이터개수표현
## Tensor Types = 정수,실수 등

In [42]:
v=tf.constant([1,2,3,4])
m=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
t=tf.constant([[[2,4],[5,6]],[[3,1],[1,2]]])

print(tf.rank(v))
print(tf.shape(v))
print(tf.rank(m))
print(tf.shape(m))
print(tf.rank(t))
print(tf.shape(t))


tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([3 3], shape=(2,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([2 2 2], shape=(3,), dtype=int32)
