In [1]:
import tensorflow as tf
import numpy as np

In [2]:
xy=np.loadtxt('data-01.csv',delimiter=',',dtype=np.float32)

In [3]:
x_data=xy[:,0:-1]
y_data=xy[:,[-1]]

In [37]:
print(x_data,"\nx_data shape :",x_data.shape)
print(y_data,"\ny_data shape :",y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape : (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape : (25, 1)


In [42]:
tf.model=tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1,input_dim=3,activation='linear'))
tf.model.compile(loss='mse',optimizer=tf.keras.optimizers.SGD(lr=5e-5))
tf.model.summary()
history=tf.model.fit(x_data,y_data,epochs=2000)

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________
Epoch 1/2000
1/1 [==============================] - 0s 2ms/step - loss: 53.5351
Epoch 2/2000
1/1 [==============================] - 0s 999us/step - loss: 52.4977
Epoch 3/2000
1/1 [==============================] - 0s 999us/step - loss: 51.5311
Epoch 4/2000
1/1 [==============================] - 0s 996us/step - loss: 50.6299
Epoch 5/2000
1/1 [==============================] - 0s 2ms/step - loss: 49.7889
Epoch 6/2000
1/1 [==============================] - 0s 2ms/step - loss: 49.0034
Epoch 7/2000
1/1 [==============================] - 0s 1ms/step - loss: 48.2692
Epoch 8/2000
1/1 [==============================] - 0s 1ms/step - loss: 47.5821
Epoch 9/

1/1 [==============================] - 0s 2ms/step - loss: 30.8055
Epoch 96/2000
1/1 [==============================] - 0s 3ms/step - loss: 30.7059
Epoch 97/2000
1/1 [==============================] - ETA: 0s - loss: 30.60 - 0s 4ms/step - loss: 30.6069
Epoch 98/2000
1/1 [==============================] - 0s 4ms/step - loss: 30.5082
Epoch 99/2000
1/1 [==============================] - 0s 3ms/step - loss: 30.4099
Epoch 100/2000
1/1 [==============================] - 0s 3ms/step - loss: 30.3121
Epoch 101/2000
1/1 [==============================] - 0s 4ms/step - loss: 30.2147
Epoch 102/2000
1/1 [==============================] - 0s 2ms/step - loss: 30.1178
Epoch 103/2000
1/1 [==============================] - 0s 2ms/step - loss: 30.0213
Epoch 104/2000
1/1 [==============================] - 0s 4ms/step - loss: 29.9252
Epoch 105/2000
1/1 [==============================] - 0s 5ms/step - loss: 29.8295
Epoch 106/2000
1/1 [==============================] - 0s 4ms/step - loss: 29.7342
Epoch 107/2

1/1 [==============================] - 0s 3ms/step - loss: 22.7404
Epoch 195/2000
1/1 [==============================] - 0s 2ms/step - loss: 22.6747
Epoch 196/2000
1/1 [==============================] - 0s 3ms/step - loss: 22.6093
Epoch 197/2000
1/1 [==============================] - 0s 3ms/step - loss: 22.5441
Epoch 198/2000
1/1 [==============================] - 0s 3ms/step - loss: 22.4792
Epoch 199/2000
1/1 [==============================] - 0s 3ms/step - loss: 22.4146
Epoch 200/2000
1/1 [==============================] - 0s 4ms/step - loss: 22.3503
Epoch 201/2000
1/1 [==============================] - 0s 2ms/step - loss: 22.2862
Epoch 202/2000
1/1 [==============================] - 0s 4ms/step - loss: 22.2224
Epoch 203/2000
1/1 [==============================] - 0s 3ms/step - loss: 22.1589
Epoch 204/2000
1/1 [==============================] - 0s 3ms/step - loss: 22.0956
Epoch 205/2000
1/1 [==============================] - 0s 4ms/step - loss: 22.0326
Epoch 206/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 17.3897
Epoch 294/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.3460
Epoch 295/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.3025
Epoch 296/2000
1/1 [==============================] - 0s 3ms/step - loss: 17.2591
Epoch 297/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.2159
Epoch 298/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.1729
Epoch 299/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.1301
Epoch 300/2000
1/1 [==============================] - 0s 2ms/step - loss: 17.0874
Epoch 301/2000
1/1 [==============================] - 0s 999us/step - loss: 17.0449
Epoch 302/2000
1/1 [==============================] - 0s 997us/step - loss: 17.0026
Epoch 303/2000
1/1 [==============================] - 0s 1ms/step - loss: 16.9604
Epoch 304/2000
1/1 [==============================] - 0s 996us/step - loss: 16.9185
Epoch 305/2000
1/1 [=====

1/1 [==============================] - 0s 2ms/step - loss: 13.8482
Epoch 392/2000
1/1 [==============================] - 0s 996us/step - loss: 13.8188
Epoch 393/2000
1/1 [==============================] - 0s 1ms/step - loss: 13.7895
Epoch 394/2000
1/1 [==============================] - 0s 7ms/step - loss: 13.7604
Epoch 395/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.7314
Epoch 396/2000
1/1 [==============================] - 0s 998us/step - loss: 13.7025
Epoch 397/2000
1/1 [==============================] - 0s 987us/step - loss: 13.6737
Epoch 398/2000
1/1 [==============================] - 0s 998us/step - loss: 13.6450
Epoch 399/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.6164
Epoch 400/2000
1/1 [==============================] - 0s 1ms/step - loss: 13.5879
Epoch 401/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5596
Epoch 402/2000
1/1 [==============================] - 0s 1ms/step - loss: 13.5314
Epoch 403/2000
1/1 [===

1/1 [==============================] - 0s 2ms/step - loss: 11.4411
Epoch 491/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.4213
Epoch 492/2000
1/1 [==============================] - 0s 999us/step - loss: 11.4016
Epoch 493/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.3819
Epoch 494/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.3623
Epoch 495/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.3429
Epoch 496/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.3235
Epoch 497/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.3041
Epoch 498/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.2849
Epoch 499/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.2657
Epoch 500/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.2466
Epoch 501/2000
1/1 [==============================] - 0s 5ms/step - loss: 11.2275
Epoch 502/2000
1/1 [=========

1/1 [==============================] - 0s 4ms/step - loss: 9.8141
Epoch 590/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.8007
Epoch 591/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.7873
Epoch 592/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.7740
Epoch 593/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.7607
Epoch 594/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.7475
Epoch 595/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.7343
Epoch 596/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.7212
Epoch 597/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.7081
Epoch 598/2000
1/1 [==============================] - 0s 997us/step - loss: 9.6951
Epoch 599/2000
1/1 [==============================] - 0s 4ms/step - loss: 9.6821
Epoch 600/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.6692
Epoch 601/2000
1/1 [=====================

1/1 [==============================] - 0s 3ms/step - loss: 8.6880
Epoch 691/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.6789
Epoch 692/2000
1/1 [==============================] - 0s 4ms/step - loss: 8.6698
Epoch 693/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.6608
Epoch 694/2000
1/1 [==============================] - 0s 4ms/step - loss: 8.6518
Epoch 695/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.6428
Epoch 696/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.6338
Epoch 697/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.6249
Epoch 698/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.6160
Epoch 699/2000
1/1 [==============================] - 0s 4ms/step - loss: 8.6072
Epoch 700/2000
1/1 [==============================] - 0s 5ms/step - loss: 8.5984
Epoch 701/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.5896
Epoch 702/2000
1/1 [=======================

1/1 [==============================] - 0s 2ms/step - loss: 7.9271
Epoch 791/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.9208
Epoch 792/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.9146
Epoch 793/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.9084
Epoch 794/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.9022
Epoch 795/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.8960
Epoch 796/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.8899
Epoch 797/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.8837
Epoch 798/2000
1/1 [==============================] - ETA: 0s - loss: 7.877 - 0s 997us/step - loss: 7.8777
Epoch 799/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.8716
Epoch 800/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.8655
Epoch 801/2000
1/1 [==============================] - 0s 5ms/step - loss: 7.8595
Epoch 802/2000
1/

1/1 [==============================] - 0s 2ms/step - loss: 7.4022
Epoch 891/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3978
Epoch 892/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3935
Epoch 893/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3892
Epoch 894/2000
1/1 [==============================] - 0s 998us/step - loss: 7.3849
Epoch 895/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3806
Epoch 896/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3763
Epoch 897/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3721
Epoch 898/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3679
Epoch 899/2000
1/1 [==============================] - 0s 997us/step - loss: 7.3636
Epoch 900/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3594
Epoch 901/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.3553
Epoch 902/2000
1/1 [===================

Epoch 991/2000
1/1 [==============================] - 0s 998us/step - loss: 7.0337
Epoch 992/2000
1/1 [==============================] - 0s 998us/step - loss: 7.0306
Epoch 993/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.0276
Epoch 994/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.0246
Epoch 995/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.0216
Epoch 996/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.0186
Epoch 997/2000
1/1 [==============================] - 0s 997us/step - loss: 7.0157
Epoch 998/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.0127
Epoch 999/2000
1/1 [==============================] - 0s 997us/step - loss: 7.0097
Epoch 1000/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.0068
Epoch 1001/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.0039
Epoch 1002/2000
1/1 [==============================] - 0s 998us/step - loss: 7.0009
Epoch 1003/2000

1/1 [==============================] - 0s 2ms/step - loss: 6.7799
Epoch 1091/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.7777
Epoch 1092/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.7756
Epoch 1093/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.7734
Epoch 1094/2000
1/1 [==============================] - 0s 998us/step - loss: 6.7713
Epoch 1095/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.7692
Epoch 1096/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.7671
Epoch 1097/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.7650
Epoch 1098/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.7629
Epoch 1099/2000
1/1 [==============================] - 0s 5ms/step - loss: 6.7608
Epoch 1100/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.7587
Epoch 1101/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.7566
Epoch 1102/2000
1/1 [=========

1/1 [==============================] - 0s 2ms/step - loss: 6.5991
Epoch 1190/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.5976
Epoch 1191/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.5961
Epoch 1192/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.5946
Epoch 1193/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.5930
Epoch 1194/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.5915
Epoch 1195/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.5900
Epoch 1196/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.5885
Epoch 1197/2000
1/1 [==============================] - 0s 5ms/step - loss: 6.5870
Epoch 1198/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.5855
Epoch 1199/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.5840
Epoch 1200/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.5825
Epoch 1201/2000
1/1 [===========

1/1 [==============================] - 0s 2ms/step - loss: 6.4693
Epoch 1289/2000
1/1 [==============================] - 0s 997us/step - loss: 6.4682
Epoch 1290/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.4671
Epoch 1291/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.4660
Epoch 1292/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.4649
Epoch 1293/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.4638
Epoch 1294/2000
1/1 [==============================] - 0s 997us/step - loss: 6.4627
Epoch 1295/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.4616
Epoch 1296/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.4605
Epoch 1297/2000
1/1 [==============================] - 0s 998us/step - loss: 6.4594
Epoch 1298/2000
1/1 [==============================] - 0s 993us/step - loss: 6.4583
Epoch 1299/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.4573
Epoch 1300/2000
1/1 [===

1/1 [==============================] - 0s 2ms/step - loss: 6.3751
Epoch 1388/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3743
Epoch 1389/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3735
Epoch 1390/2000
1/1 [==============================] - 0s 990us/step - loss: 6.3727
Epoch 1391/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3719
Epoch 1392/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3711
Epoch 1393/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3703
Epoch 1394/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3695
Epoch 1395/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3687
Epoch 1396/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.3679
Epoch 1397/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3671
Epoch 1398/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.3663
Epoch 1399/2000
1/1 [=========

1/1 [==============================] - 0s 2ms/step - loss: 6.3062
Epoch 1487/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.3056
Epoch 1488/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3050
Epoch 1489/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3044
Epoch 1490/2000
1/1 [==============================] - 0s 999us/step - loss: 6.3038
Epoch 1491/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3033
Epoch 1492/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3027
Epoch 1493/2000
1/1 [==============================] - 0s 997us/step - loss: 6.3021
Epoch 1494/2000
1/1 [==============================] - 0s 991us/step - loss: 6.3015
Epoch 1495/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.3009
Epoch 1496/2000
1/1 [==============================] - 0s 999us/step - loss: 6.3003
Epoch 1497/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.2998
Epoch 1498/2000
1/1 [===

1/1 [==============================] - 0s 2ms/step - loss: 6.2554
Epoch 1586/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.2549
Epoch 1587/2000
1/1 [==============================] - 0s 996us/step - loss: 6.2545
Epoch 1588/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.2541
Epoch 1589/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.2536
Epoch 1590/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.2532
Epoch 1591/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.2528
Epoch 1592/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.2523
Epoch 1593/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.2519
Epoch 1594/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.2515
Epoch 1595/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.2510
Epoch 1596/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.2506
Epoch 1597/2000
1/1 [=========

1/1 [==============================] - 0s 2ms/step - loss: 6.2176
Epoch 1685/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.2173
Epoch 1686/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.2169
Epoch 1687/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.2166
Epoch 1688/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.2163
Epoch 1689/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.2160
Epoch 1690/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.2156
Epoch 1691/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.2153
Epoch 1692/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.2150
Epoch 1693/2000
1/1 [==============================] - 0s 5ms/step - loss: 6.2147
Epoch 1694/2000
1/1 [==============================] - 0s 987us/step - loss: 6.2144
Epoch 1695/2000
1/1 [==============================] - 0s 5ms/step - loss: 6.2140
Epoch 1696/2000
1/1 [=========

1/1 [==============================] - 0s 1ms/step - loss: 6.1893
Epoch 1784/2000
1/1 [==============================] - 0s 998us/step - loss: 6.1891
Epoch 1785/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1888
Epoch 1786/2000
1/1 [==============================] - 0s 997us/step - loss: 6.1886
Epoch 1787/2000
1/1 [==============================] - 0s 998us/step - loss: 6.1883
Epoch 1788/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1881
Epoch 1789/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1878
Epoch 1790/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1876
Epoch 1791/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1874
Epoch 1792/2000
1/1 [==============================] - 0s 997us/step - loss: 6.1871
Epoch 1793/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.1869
Epoch 1794/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1866
Epoch 1795/2000
1/1 [===

1/1 [==============================] - 0s 2ms/step - loss: 6.1680
Epoch 1883/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1678
Epoch 1884/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1676
Epoch 1885/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1674
Epoch 1886/2000
1/1 [==============================] - 0s 997us/step - loss: 6.1673
Epoch 1887/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1671
Epoch 1888/2000
1/1 [==============================] - 0s 999us/step - loss: 6.1669
Epoch 1889/2000
1/1 [==============================] - 0s 993us/step - loss: 6.1667
Epoch 1890/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1665
Epoch 1891/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.1664
Epoch 1892/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1662
Epoch 1893/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.1660
Epoch 1894/2000
1/1 [=====

1/1 [==============================] - 0s 3ms/step - loss: 6.1519
Epoch 1982/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1517
Epoch 1983/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.1516
Epoch 1984/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1514
Epoch 1985/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.1513
Epoch 1986/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1511
Epoch 1987/2000
1/1 [==============================] - 0s 997us/step - loss: 6.1510
Epoch 1988/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.1509
Epoch 1989/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1507
Epoch 1990/2000
1/1 [==============================] - 0s 997us/step - loss: 6.1506
Epoch 1991/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1505
Epoch 1992/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.1503
Epoch 1993/2000
1/1 [=======

In [43]:
print("Your score will be",tf.model.predict([[100,70,101]]))
print("Other scores will be",tf.model.predict([[60,70,110],[90,100,80]]))

Your score will be [[187.14232]]
Other scores will be [[180.74298]
 [175.48419]]
